Work with data
dh-center/Digital-Portraits pull request #28
Opened 2021-05-17 15:36 UTC by Zhenya-Ko

2021-06-03 13:11 UTC, nikmel2803 approved these changes

2021-06-03 13:11 UTC, nikmel2803 commented on src/allpaintercards.css
> +
стили, который относятся к компоненту, должны быть в отдельном файле, в данном случае Loader.css

2021-06-03 13:11 UTC, nikmel2803 commented on src/MainContent.js
> +    const [filteredData, setfilteredData] = useState('')
не совсем правильно
у тебя должно быть два стейта в этом компоненте: data и filters. 
 filteredData можно посчитать на ходу из этих двух стейтов

2021-06-03 13:11 UTC, nikmel2803 commented on src/MainContent.js
> +        fetch('http://localhost:3001', {
надо вынести этот адрес в переменные среды, потому что этот адрес правильный только для твоего локального окружения, на сервере нужен другой
почитай про это в доках
https://create-react-app.dev/docs/adding-custom-environment-variables/

2021-06-03 13:11 UTC, nikmel2803 commented on src/MainContent.js
> +            <Filters filterData={handleSlide} resetcards={handleClick}
тут тоже не совсем верно
правильнее передавать в этот компонент два пропа:
value — где будут содержаться текущие фильтры
и onChange — там будет обработчик, который будет вызываться при изменении фильтров. В этот обработчик надо запихнуть setFilters

2021-06-03 13:11 UTC, nikmel2803 commented on src/MainContent.js
> +            <AllPaintercards data={data} filtered={filteredData} />
и вот этому компоненту нужно только отфильтрованные данные передавать

2021-06-03 13:11 UTC, nikmel2803 requested changes
мисклик

2021-06-03 13:34 UTC, Zhenya-Ko commented on src/MainContent.js
> +            <AllPaintercards data={data} filtered={filteredData} />
Почему? У меня же первый рендер, там просто все данные, а не отфильтрованные. Пользователь потом сам фильтрует, то, что нужно.

2021-06-03 13:36 UTC, Zhenya-Ko commented on src/MainContent.js
> +    const [filteredData, setfilteredData] = useState('')
Не совсем поняла, что ты имеешь тут ввиду.

2021-06-03 13:37 UTC, nikmel2803 commented on src/MainContent.js
> +    const [filteredData, setfilteredData] = useState('')
лучше убрать стейт filteredData и сделать стейт filters
сделай так, увидишь что код станет проще
и посмотри ещё коммент к компоненту Filters

2021-06-04 13:03 UTC, nikmel2803 commented on src/AllPainterCards.js
> +            <Rendercards data={props.data} filtered={props.filtered} />
у тебя уже нет props.filtered

2021-06-04 13:03 UTC, nikmel2803 commented on src/allpaintercards.css
> +
надо их удалить отсюда

2021-06-04 13:03 UTC, nikmel2803 commented on src/MainContent.js
> +    const [data, setdata] = useState([])
setData

2021-06-04 13:03 UTC, nikmel2803 commented on src/MainContent.js
> +    const [filters, setfilter] = useState(null)
setFilters

2021-06-04 13:17 UTC, nikmel2803 approved these changes

2021-06-05 11:39 UTC, merged